substitutions:  
  device_name: smart-plug-ind
  friendly_name: Smart Plug Ind
  s_ip: 192.168.x.x


esphome:
  name: $device_name
  friendly_name: $friendly_name
  #platformio_options:
    #board_build.f_cpu: 60000000L
  on_boot:
    priority: 600
    then:       
      - lock.unlock: child_lock      
      - if: # Relay Status OFF
         condition:
           - switch.is_off: relay
         then:
           - light.turn_off: power_led
         else:
           - light.turn_on: power_led
           - delay: 5s    
           - light.turn_on: 
              id: power_led
              brightness: 70%
      - number.set: 
          id: set_num
          value: 5
      - script.execute: power_save
bk72xx:
  board: generic-bk7231t-qfn32-tuya  
  framework:
    version: latest

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  password: !secret hotspot_pw

wifi:
  id: iptime
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: HIGH
  fast_connect: True
  manual_ip: 
   static_ip: $s_ip 
   gateway: 192.168.x.x
   subnet: 255.255.255.0
   
  on_connect:
    then:
      - light.turn_on:
          id: power_led
          flash_length: 500ms
      - button.press: wake_up
  on_disconnect:
    then:
      - if: # Relay Status OFF
         condition:
           - switch.is_off: relay
         then:
           - light.turn_off: power_led
         else:
           - light.turn_on: power_led
           - delay: 5s    
           - light.turn_on: 
              id: power_led
              brightness: 70%

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: $device_name
    password: !secret hotspot_pw

captive_portal:
web_server:
  

#mqtt:
  #broker: 192.168.1.102
  #username: !secret mqtt_id
  #password: !secret mqtt_password

uart:
  id: uart_bus
  tx_pin: P11
  rx_pin: P10
  baud_rate: 4800
  stop_bits: 1

time:
  - platform: homeassistant
    id: homeassistant_time

binary_sensor:
  - platform: status
    name: "API Connection"
    id: c_status
    on_release:
      then:
        - if:
              condition:
                for:
                  time: 60s
                  condition:
                    - binary_sensor.is_off: c_status
              then:
                - button.press: re_start
  - platform: template
    id: binary_save
    name: Power Save Watchdog
    lambda: |-
      if (id(power_save).is_running()){
      return true;
      } else {
      return false;
      }
  
  # Button on the front is pressed and then toggle relay           
  - platform: gpio
    device_class: power
    internal: True
    pin:
      number: 9
      mode: INPUT_PULLDOWN
      inverted: True
    name: Button # Name to make button visible in HA
    on_click:      
      - min_length: 50ms
        max_length: 1000ms
        then:          
          - if: 
              condition:
               - lock.is_unlocked: child_lock
              then: 
               - switch.toggle: relay
              else:
                - repeat:
                    count: 3
                    then:
                      - light.turn_on: power_led
                      - delay: 0.5s
                      - light.turn_off: power_led
                      - delay: 0.5s      
          - if: # Relay Status OFF
                condition:
                  - switch.is_off: relay
                then:
                  - light.turn_off: power_led
                else:
                - light.turn_on: power_led
                - delay: 5s    
                - light.turn_on: 
                    id: power_led
                    brightness: 70%
          - script.execute: power_save

    on_multi_click:
      - timing:
        - ON for at least 5s   
        - OFF for at least 0.5s     
        then:          
          - if: # if lock is lock, do unlock
              condition:
                lock.is_locked: child_lock
              then:                  
                  - lock.unlock: child_lock
                  - logger.log: "unlock"
                  - repeat:
                      count: 2
                      then:
                        - light.turn_on: power_led
                        - delay: 0.5s
                        - light.turn_off: power_led
                        - delay: 0.5s      
                  - if: # Relay Status OFF
                      condition:
                        - switch.is_on: relay
                      then:
                        - light.turn_on: power_led
                        - delay: 5s    
                        - light.turn_on: 
                            id: power_led
                            brightness: 70%
              else: # if lock is unlock, do lock                  
                  - lock.lock: child_lock
                  - logger.log: "locked"
                  - repeat:
                      count: 3
                      then:
                        - light.turn_on: power_led
                        - delay: 0.5s
                        - light.turn_off: power_led
                        - delay: 0.5s 
                  - if: # Relay Status OFF
                      condition:
                        - switch.is_on: relay
                      then:
                        - light.turn_on: power_led
                        - delay: 5s    
                        - light.turn_on: 
                            id: power_led
                            brightness: 70%
      - timing:
        - ON for at least 10s   
        - OFF for at least 0.5s
        then:
          - switch.turn_on: s_safe
sensor:
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    internal: true
    update_interval: 300s
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
    device_class: ""
    icon: mdi:wifi

  - platform: total_daily_energy
    name: 'Total Daily Energy'
    power_id: power
    unit_of_measurement: 'kWh'
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    icon: mdi:counter
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
      
  - platform: internal_temperature
    name: "Internal Temperature"

  - platform: bl0942
    uart_id: uart_bus
    voltage:
      name: 'Voltage'
    current:
      name: 'Current'
    power:
      name: 'Power'
      id: power
      accuracy_decimals: 2
      on_value:              
        - if:
            condition:              
              for:
                time: 15ms
                condition:
                  and:
                    - switch.is_on: switch_olp
                    - lambda: return (id(power).state >= 4000);
            then:
              - switch.turn_off: relay      
        - if:
            condition:              
              for:
                time: 5min
                condition:
                  and:
                    - switch.is_on: switch_olp
                    - lambda: return (id(power).state >= 3500 );
            then:
              - switch.turn_off: relay
        - if:
            condition:              
              for:
                time: 60min
                condition:
                  and:
                    - switch.is_on: switch_olp
                    - lambda: return (id(power).state >= 3000 );
            then:
              - switch.turn_off: relay      
        - if:
            condition:
              and:
                - switch.is_on: relay
                - binary_sensor.is_off: binary_save
            then:
              - script.execute: power_save
    energy:
      name: 'Energy'
    frequency:
      name: "Frequency"
      accuracy_decimals: 2
    update_interval: 3s

number:
  - platform: template
    name: "Set Stanby W"
    id: set_num
    optimistic: true
    icon: mdi:numeric
    min_value: 0
    max_value: 100
    unit_of_measurement: W
    step: 5
    on_value:
      then:
        - script.execute: power_save

text_sensor:
  - platform: version
    name: "Esphome Version"
  - platform: wifi_info
    ip_address:
     name: Device IP Address
    mac_address:
      name: ESP Mac Wifi Address

light:
  - platform: binary
    name: "Power LED"
    id: power_led
    output: led_out
    restore_mode: ALWAYS_OFF
    internal: true

output:
  - platform: libretiny_pwm
    id: led_out
    pin: 
      number: 6
      inverted: true
    frequency: 120Hz

button:    
  - platform: restart
    name: "Restart"
    id: re_start
    entity_category: diagnostic
  - platform: wake_on_lan
    name: "Start the Server"
    id: wake_up
    target_mac_address: !secret server
    on_press:
      then:
        - logger.log: "Wake UP the Server"

switch:
# Relay itself
  - platform: gpio
    name: "switch"
    pin: GPIO26
    id: relay
    icon: mdi:power-socket-de
    device_class: outlet
    on_turn_on:
      - light.turn_on: 
          id: power_led
          brightness: 70%
      - script.execute: power_save
    on_turn_off:
      - light.turn_off: power_led
  # Stanby Power Save
  - platform: template
    name: "Save Standby Power"    
    id: switch_save
    icon: mdi:toggle-switch
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: true
    on_turn_on:    
      - script.execute: power_save
    on_turn_off: 
      - script.stop: power_save
    # Overload Protect
  - platform: template
    name: "OverLoad Protection"    
    id: switch_olp
    restore_mode: RESTORE_DEFAULT_ON
    icon: mdi:toggle-switch
    optimistic: true

  - platform: safe_mode
    internal: true
    id: s_safe
    name: Safe Mode Boot
    entity_category: diagnostic   

lock:  
  - platform: template
    name:  Child's Lock
    id: child_lock
    optimistic: true

script:
  - id: power_save
    mode: restart
    then:
      - delay: 300s
      - if:
          condition:
             and:              
               - switch.is_on: relay
               - switch.is_on: switch_save
               - lambda: return (id(power).state <= id(set_num).state );
          then: 
            - switch.turn_off: relay

